# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/fcc-book
    docker:
        - image: circleci/node:4.8.2
    steps:
        - checkout

        - restore_cache:
            key: ee-client-{{ checksum "./client/package.json" }}
        - restore_cache:
            key: ee-server-{{ checksum "./server/package.json" }}

        - run:
            name: install client dependencies
            command: 'cd client && npm install'      
        - run:
            name: install server dependencies
            command: 'cd server && npm install'

        - save_cache:
            key: ee-client-{{ checksum "./client/package.json" }}
            paths:
                - ./client/node_modules
        - save_cache:
            key: ee-server-{{ checksum "./server/package.json" }}
            paths:
                - ./server/node_modules
        
        - run:
            name: building client
            command: 'cd ./client && npm run build'
        
        - store_artifacts:
            path: ./client/build
            prefix: build